### ISSUE TITLE
Supprimer la nécéssité d'ionCube

### ISSUE THREAD

**Issue by Krafting** [kevinguiot/craftmycms#2]
Bonjour,

Je suis un très ancien utilisateur de CraftMyCMS, et j'ai essayé de remètre en ligne un ancien site internet basé sur CMC. (Principalement pour moi même, pas en production). Je ne sais pas si vous êtes toujours actif mais je tente quand même! 

J'ai remarqué que ionCube a été retirer sur tous les fichiers sauf le include/init.php, serait il possible de fournir le code source entier de ce fichier aussi, et ainsi supprimé la dépendance pour ionCube?

Merci beaucoup à vous et bonne journée!

**Comment by kevinguiot** [comment]
Bonjour @Krafting, je me souviens de vous.

Je vais voir prochainement pour enlever le fichier encrypté.

Belle journée à vous.

Kévin.

**Comment by Krafting** [comment]
Magnifique! 

Il y aurtais aussi possibilité de posté le plugin Forum et Vote que vous vendiez à l'époque ? Si possible décrypté aussi!

**Comment by noysteque** [comment]
Du coup c'est plus d'actualité de l'enlever?

**Comment by Krafting** [comment]
> Du coup c'est plus d'actualité de l'enlever?

Je ne sais pas, nous attendons toujours...

**Comment by kevinguiot** [comment]
Bonjour à tous les deux,

Je vous avoue avoir tout simplement oublié, étant donné qu'aujourd'hui, j'ai des projets bien plus récents que CraftMyCMS. 

Je me mets sans faute un rappel ce week-end, en espérant avoir encore les fichiers décryptés.

Belle soirée à vous et bon week-end 😀

**Comment by Krafting** [comment]
> Bonjour à tous les deux,
> 
> Je vous avoue avoir tout simplement oublié, étant donné qu'aujourd'hui, j'ai des projets bien plus récents que CraftMyCMS.
> 
> Je me mets sans faute un rappel ce week-end, en espérant avoir encore les fichiers décryptés.
> 
> Belle soirée à vous et bon week-end 😀

Magnifique a entendre!

Bien sur que les projets d'aujourdhui sont plus important qu'un bon vieux CMS!

Bonne soirée et bon week end aussi! 😁

**Comment by kevinguiot** [comment]
C'est rajouté @Krafting  👍 

Belle fin de journée à tous,
